#!/bin/bash
 
#SBATCH -o "v100.txt"
#SBATCH -e "ev100.txt"
#SBATCH --time=3:00:00
#SBATCH --partition=courses-gpu
#SBATCH --gres=gpu:v100-sxm2:1

source /home/rowan.t/miniconda3/bin/activate
conda activate myenv

# Run experiments
echo "Running cnn.py on cifar with stochastic nsys" >> job_log_V100.txt
nsys profile -o v100_cifar_sto python3 cnn.py cifar stochastic

echo "Running cnn.py on cifar with adam nsys" >> job_log_V100.txt
nsys profile -o v100_cifar_adam python3 cnn.py cifar adam

echo "Running cnn.py on cifar with adagrad nsys" >> job_log_V100.txt
nsys profile -o v100_cifar_ada python3 cnn.py cifar adagrad

echo "Running cnn.py on fashionmnist with stochastic nsys" >> job_log_V100.txt
nsys profile -o v100_fasion_sto python3 cnn.py fashionmnist stochastic

echo "Running cnn.py on fashionmnist with adam nsys" >> job_log_V100.txt
nsys profile -o v100_fasion_adam python3 cnn.py fashionmnist adam

echo "Running cnn.py on fashionmnist with adagrad nsys" >> job_log_V100.txt
nsys profile -o v100_fasion_ada python3 cnn.py fashionmnist adagrad

exit 0


